Resources:
  MyDB:
    Type: "AWS::RDS::DBInstance"
    Properties: 
      AllocatedStorage: "20"
      AvailabilityZone: "eu-central-1a"
      DBInstanceClass: "db.t2.micro"
      DBName: "MySQLDB"
      Engine: "mysql"
      EngineVersion: "5.7.19"
      MasterUsername: "root"
      MasterUserPassword: "rootpwd111"