Resources:
  MyDB:
    Type: "AWS::RDS::DBInstance"
    Properties: 
      AllocatedStorage: "20"
      AvailabilityZone: "eu-central-1a"
      DBInstanceClass: "db.t2.micro"
      DBName: "MySQLDB"
      Engine: "mysql"
      EngineVersion: "5.7.19"
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref MySecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref MySecret, ':SecretString:password}}' ]]
  MyLC:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    DependsOn: "MyLB"
    Properties: 
      ImageId: "ami-0cc0a36f626a4fdf5"
      InstanceType: "t2.micro"
      KeyName: "matrix"
      LaunchConfigurationName: "AutoLC-1"
      PlacementTenancy: "default"
      SecurityGroups: 
        - "launch-wizard-2"
      UserData:
        Fn::Base64:
          !Sub | 
            #!/bin/bash          
            cd /home/ubuntu
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install nginx -y
            sudo apt-get install python3 -y
            sudo apt-get install python3-pip -y
            sudo pip3 install Django==2.1.7 
            sudo pip3 install pymysql 
            git clone https://github.com/dmitiyoleynik/python
            cd python
            python3 replace.py MySQLDB root rootpwd111 ${MyDB.Endpoint.Address}
            cd hello
            python3 manage.py makemigrations 
            python3 manage.py migrate 
            python3 manage.py runserver 0.0.0.0:5000
  MyLB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    DependsOn: "MyDB"
    Properties: 
      Listeners: 
        - LoadBalancerPort: "80"
          InstancePort: "5000"
          Protocol: "HTTP"
      HealthCheck:
        HealthyThreshold: 10
        Interval: 30
        Target: "TCP:80"
        Timeout: 5 
        UnhealthyThreshold: 2
      LoadBalancerName: "AutoLB-1"
      Subnets:
        - subnet-0339287e
        - subnet-31f4107d
        - subnet-5760bb3d
      SecurityGroups: 
        - "sg-0eb7374edf5105b8d"
  MyASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: "MyLC"
    Properties: 
      AutoScalingGroupName: "AutoASG-1"
      AvailabilityZones:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      HealthCheckGracePeriod: 200
      LaunchConfigurationName: "AutoLC-1"
      LoadBalancerNames: 
        - "AutoLB-1"
      MaxSize: 2
      MinSize: 1
  MySecret:      
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: "Secret key for RDS instance"
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
  MySecretAttachment:      
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref MySecret
      TargetId: !Ref MyDB
      TargetType: AWS::RDS::DBInstance