Type: AWS::SecretsManager::Secret
Properties: 
  Description: "Secret key for RDS instance"
  GenerateSecretString: 
    SecretStringTemplate: '{"username": "admin"}'
    GenerateStringKey: 'password'
    PasswordLength: 16
    ExcludeCharacters: '"@/\'
   
SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref MyRDSInstanceRotationSecret
      TargetId: !Ref MyDBInstance
      TargetType: AWS::RDS::DBInstance